# Install & Import

In [4]:
!pip install -q sentence-transformers faiss-gpu-cu12 rank_bm25

In [5]:
import pandas as pd
import numpy as np
import faiss

In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/config.json
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/README.md
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/tokenizer_config.json
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/pytorch_model.bin
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/special_tokens_map.json
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.gitattributes
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/vocab.txt
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/flax_model.msgpack
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/config
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/packed-refs
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/HEAD
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/index
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/description
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/info/exclude
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/refs/heads/main
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/refs/remotes/origin/HEAD
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-merge-commit.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/post-merge
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-push
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/prepare-commit-msg.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/update.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-push.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-rebase.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-applypatch.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/post-commit
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/post-checkout
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/push-to-checkout.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-commit.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/commit-msg.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/post-update.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/pre-receive.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/fsmonitor-watchman.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/hooks/applypatch-msg.sample
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/lfs/objects/bc/60/bc6033077e458cf98490d51883382806373325919e7b5dd12f4dd694dcd667cd
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/lfs/objects/3a/e1/3ae17b87eda3d184502a821fddff43d82feb7c206f665a851c491ec715b497ed
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/logs/HEAD
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/logs/refs/heads/main
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/logs/refs/remotes/origin/HEAD
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/c5/13f1ea4ba4173d62ed106cf3788a8444eba109
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/b2/cfda50a1a9fc7919e7444afbb52610d268af92
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/07/f0db3339ad9053dc95b284c4ae14e014efff89
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/10/13e0496f607588948eb388af2b2a3622e681da
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/25/1097b23dcdd092e257f78e38ce1f453702e396
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/42/4108d39bc0893d121b5fb82aa1040d18e5f40e
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/e7/b0375001f109a6b8873d756ad4f7bbb15fbaa5
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/6e/fbd6a2c22fd9ceff5df9abed8085fb1e266964
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/88/bc4f74b33a2073abc9a66cb532b889448ac3ed
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/d6/99711d884c16db686245dffb53739ddf85119c
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/fb/140275c155a9c7c5a3b3e0e77a9e839594a938
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/58/8b01a83959436e6051d2133d8e9ecdcb28b1a5
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/5a/da1949e136ae805beb30608607c6b84645969a
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/9d/d7123c0cb6efe04db8f765466e66c4b483280b
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/3d/461ad0e886242b80a7080910bc0d2d9551559e
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/d7/b8c495dd9e6df27bfd6a47dad7e33da0850a5b
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/21/190b32ec3921c25c336fbaed521d3a7e9b5a03
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/d3/c87ff86d02a312dc895fff50a815f5aaaee56b
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/01/15e9135ce086ae91881143a2ed29333d3178fd
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/01/1817017316364ccf56bcecf154352ed88650cd
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/9c/63cf1a91e6a9b3a0a093808b8067becd38d39f
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/ee/319b374bcbcdea4752e94ce7ecc0e19de616b9
/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2/.git/objects/2f/d98132fd4620f90908272d9a9e6b2626e83491
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/config.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/README.md
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/tokenizer.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/tokenizer_config.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/sparse_linear.pt
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/sentence_bert_config.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/pytorch_model.bin
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/long.jpg
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/config_sentence_transformers.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/colbert_linear.pt
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/modules.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/special_tokens_map.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/.gitattributes
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/sentencepiece.bpe.model
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/1_Pooling/config.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/model.onnx
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/config.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/tokenizer.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/Constant_7_attr__value
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/tokenizer_config.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/special_tokens_map.json
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/model.onnx_data
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/onnx/sentencepiece.bpe.model
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/imgs/bm25.jpg
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/imgs/others.webp
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/imgs/miracl.jpg
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/imgs/long.jpg
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/imgs/mkqa.jpg
/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3/imgs/nqa.jpg
/kaggle/input/competitions/llm-agentic-legal-information-retrieval/sample_submission.csv
/kaggle/input/competitions/llm-agentic-legal-information-retrieval/laws_de.csv
/kaggle/input/competitions/llm-agentic-legal-information-retrieval/val.csv
/kaggle/input/competitions/llm-agentic-legal-information-retrieval/court_considerations.csv
/kaggle/input/competitions/llm-agentic-legal-information-retrieval/train.csv
/kaggle/input/competitions/llm-agentic-legal-information-retrieval/test.csv

# load dataset

In [7]:
train = pd.read_csv(dirname+"/train.csv")
val = pd.read_csv(dirname+"/val.csv")
test = pd.read_csv(dirname+"/test.csv")
laws_de = pd.read_csv(dirname+"/laws_de.csv")
court_considerations = pd.read_csv(dirname+"/court_considerations.csv")

In [8]:
print(f'''
"train":{train.shape},
"\nlaws_de:"{laws_de.shape},
"\ncourt_considerations:"{court_considerations.shape}''')

"train":(1139, 3),
"
laws_de:"(175933, 3),
"
court_considerations:"(2476315, 2)

In [9]:
train.head()

,query_id,query,gold_citations
0,train_0001,Die A AG betreibt seit den 1970er-Jahren auf d...,Art. 10a Abs. 1 USG;Art. 2 Abs. 1 UVPV;Art. 10...
1,train_0002,Die Alpha Consulting AG kann nun ihr Grundstüc...,Art. 975 ZGB;Art. 974 Abs. 2 ZGB;Art. 973 ZGB;...
2,train_0003,Das Kompetenzzentrum Völkerstrafrecht bei der ...,Art. 264m StGB
3,train_0004,Die Linzer Stadtbahn AG ('LiSA') ist die priva...,Art. 176 Abs. 1 IPRG;Art. 186 Abs. 1 IPRG;Art....
4,train_0005,Die Stadt Winterthur beschloss am 10. Februar ...,Art. 93 Abs. 1 BGG;Art. 89 Abs. 1 BGG;Art. 89 ...

In [10]:
laws_de.head()

,citation,text,title
0,Art. 1 112,Die Einwohnergemeinde Bern tritt der Schweizer...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
1,Art. 2 112,Die Einwohnergemeinde Bern wird ferner der Sch...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
2,Art. 3 Abs. 1 112,1 Falls die Schweizerische Eidgenossenschaft z...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
3,Art. 3 Abs. 2 112,2 Durch Anlage des neuen Verwaltungsgebäudes a...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
4,Art. 4 Abs. 1 112,1 Die Einwohnergemeinde Bern übernimmt im fern...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...

In [11]:
court_considerations.head()

                   citation                                               text
0  BGE 139 I 2 E. 1.12.2011  betr. Verweigerung der Beiladung seien gutzuhe...
1          BGE 139 I 2 E. 2  Eventualiter sei die Rückweisung an die Vorins...
2        BGE 139 I 2 E. 5.1  In der Sache ist vorweg zu prüfen, ob der Ents...
3        BGE 139 I 2 E. 5.2  Art. 34 Abs. 1 BV gewährleistet in allgemeiner...
4        BGE 139 I 2 E. 5.3  Im vorliegenden Fall geht es nicht um die Gült...

laws_de is like law book

court_considerations is like case studies

| laws_de          | court_considerations |
| ---------------- | -------------------- |
| Rules            | Interpretations      |
| Short text       | Long text            |
| Structured       | Complex              |
| Easier retrieval | Harder retrieval     |

# Prepare Corpus

In [12]:
laws_de.columns

Index(['citation', 'text', 'title'], dtype='object')

In [13]:
corpus = laws_de.rename(columns={"citation":"id"})

In [14]:
corpus["full_text"] = corpus["title"]*3 + "" +corpus["text"] # More weight to title
docs = corpus["full_text"].tolist()
docs_id = corpus["id"].tolist()
title = corpus["title"].tolist()

# Model Initialization

In [15]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
hf_token = user_secrets.get_secret("HF_Token")

In [16]:
from huggingface_hub import login
login(token=hf_token)

In [17]:
# cross Lingual
from sentence_transformers import SentenceTransformer, CrossEncoder
embed_model =SentenceTransformer("/kaggle/input/models/yethukmutt/bge-m3/transformers/m3/1/bge-m3") # best choice
reranker = CrossEncoder("/kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2")

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: /kaggle/input/models/johnsonhk88/cross-encoderms-marco-minilm-l-6-v2/transformers/v1/1/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.